### ISSUE TITLE
Linux环境下不出图

### ISSUE THREAD

**Issue by PixelQz** [AquaIndigo/GAMES101-rs#1]
大佬你好。我测试的环境是debian12系统。在作业3及之后的作业中，每个作业都能编译运行成功，但却没有模型图片出来。需要怎么设置？

**Comment by Indigo2233** [comment]
我是在Arch环境下开发的，在hw3中运行`cargo run`能成功出图（我更新了Cargo的opencv版本，旧版无法编译成功），你可以检查一下是不是opencv的版本问题，或者不依赖opencv而是引入一些图像库，重新编写输出的部分即可。

**Comment by PixelQz** [comment]
感谢大佬回信。我是小白，不懂得那么多，往后我再试试。
---- Replied Message ----
| From | Su ***@***.***> |
| Date | 12/03/2023 16:21 |
| To | AquaIndigo/GAMES101-rs ***@***.***> |
| Cc | Pixel-Q ***@***.***>,
Author ***@***.***> |
| Subject | Re: [AquaIndigo/GAMES101-rs] Linux环境下不出图 (Issue #1) |

我是在Arch环境下开发的，在hw3中运行cargo run能成功出图（我更新了Cargo的opencv版本，旧版无法编译成功），你可以检查一下是不是opencv的版本问题，或者不依赖opencv而是引入一些图像库，重新编写输出的部分即可。

**Comment by Indigo2233** [comment]
可以试试编译运行hw5，不依赖外部库输出一个ppm文件

**Comment by PixelQz** [comment]
生成ppm是可以，但这个有什么用吗？
---- Replied Message ----
| From | Su ***@***.***> |
| Date | 12/10/2023 00:25 |
| To | AquaIndigo/GAMES101-rs ***@***.***> |
| Cc | Pixel-Q ***@***.***>,
Author ***@***.***> |
| Subject | Re: [AquaIndigo/GAMES101-rs] Linux环境下不出图 (Issue #1) |

可以试试编译运行hw5，不依赖外部库输出一个ppm文件

**Comment by Indigo2233** [comment]
ppm就是一种图像格式

**Comment by PixelQz** [comment]
你的意思是让我学hw5那样重新在hw3那里重新编写输出部分输出ppm
---- Replied Message ----
| From | Su ***@***.***> |
| Date | 12/10/2023 13:42 |
| To | AquaIndigo/GAMES101-rs ***@***.***> |
| Cc | Pixel-Q ***@***.***>,
Author ***@***.***> |
| Subject | Re: [AquaIndigo/GAMES101-rs] Linux环境下不出图 (Issue #1) |

ppm就是一种图像格式

**Comment by PixelQz** [comment]
貌似搞错了点什么。原来你这个就是输出一个图片罢了。我还以为是生成那种显示整个模型能旋转那种图片窗口。
---- Replied Message ----
| From | Su ***@***.***> |
| Date | 12/10/2023 13:42 |
| To | AquaIndigo/GAMES101-rs ***@***.***> |
| Cc | Pixel-Q ***@***.***>,
Author ***@***.***> |
| Subject | Re: [AquaIndigo/GAMES101-rs] Linux环境下不出图 (Issue #1) |

ppm就是一种图像格式

**Comment by PixelQz** [comment]
打扰了#囧

---- Replied Message ----
| From | Su ***@***.***> |
| Date | 12/10/2023 13:42 |
| To | AquaIndigo/GAMES101-rs ***@***.***> |
| Cc | Pixel-Q ***@***.***>,
Author ***@***.***> |
| Subject | Re: [AquaIndigo/GAMES101-rs] Linux环境下不出图 (Issue #1) |

ppm就是一种图像格式

**Comment by Indigo2233** [comment]
我是参照games101的输出形式写的
